name: request_track
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file: ^6.1.4
  get: ^4.6.5
  remixicon: ^1.0.0
  google_fonts: ^3.0.1
  blur: ^3.1.0
  toggle_switch: ^2.0.1
  tuple: ^2.0.0
  shared_preferences: ^2.0.15
  simple_animations: ^4.0.2
  file_picker: ^4.6.0
  image_picker: ^0.8.5+3
  sliding_sheet: ^0.5.2
  open_file: ^3.2.1
  flutter_pdfview: ^1.2.2
  bootstrap_icons: ^1.8.1
  pdfx: ^2.0.1+2
  flutter_platform_widgets: ^1.20.0
  dio: ^4.0.6
  loading_animation_widget: ^1.2.0+1
  flutter_rounded_date_picker: ^3.0.2
  intl: ^0.17.0
  day_night_time_picker: ^1.0.5
  dart_jsonwebtoken: ^2.4.1
  skeletons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  rename: ^2.0.1
  logger: ^1.1.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - fonts/