name: request_track
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  blur: ^3.1.0
  bootstrap_icons: ^1.10.5+2
  cupertino_icons: ^1.0.2
  dart_jsonwebtoken: ^2.8.2
  day_night_time_picker: ^1.3.0
  dio: ^5.2.1+1
  # file: ^7.0.0
  file_picker: ^5.2.0
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.1
  flutter_platform_widgets: ^3.3.5
  flutter_rounded_date_picker: ^3.0.4
  get: ^4.6.5
  google_fonts: ^5.1.0
  image_picker: ^0.8.9
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  open_file: ^3.3.2
  pdfx: ^2.3.0
  remixicon: ^1.0.0
  shared_preferences: ^2.1.2
  simple_animations: ^5.0.2
  skeletons: ^0.0.3
  toggle_switch: ^2.1.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  logger: ^1.4.0
  rename: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - fonts/
